### ISSUE TITLE
Exercise 2 is not working

### ISSUE THREAD

**Issue by benze** [robertkowalski/learnyoucouchdb#1]
Or I do not understand the instructions correctly.  According to the exercise, a new db called:
http://localhost:5894/things-learn-couchdb

should have been created and populated.  However no such DB exists, or was created.  Nor were any error msgs generated/issued.

Additionally, the text has a typo - it should read port 5984 and not 5894.

**Comment by robertkowalski** [comment]
Thank you so much for your feedback!

I released 1.0.1which should create the database now (before that it was on the verify run): 26e0fccbc5f54b07589651ae4ca46527ebf3dc4d

I also fixed the typo in f897d1e3569385e88703f619b2d5d2907a242936

Can you test again?

**Comment by benze** [comment]
Works now.
