### ISSUE TITLE
Too steep of a learning curve?

### ISSUE THREAD

**Issue by sudodoki** [robertkowalski/learnyoucouchdb#2]
Got kinda stuck almost instantly at 'Start Apache CouchDB' :confused: . Maybe, for the first task it should be something like [Going's native](https://github.com/rvagg/goingnative/blob/master/exercises/am_i_ready/problem.md.tmpl) one, which just states about setup needed for workshopper?

**Comment by robertkowalski** [comment]
Sounds good! PR welcome!

**Comment by sudodoki** [comment]
:bow:

**Comment by robertkowalski** [comment]
I finally had time for this task! Thanks for your feedback @sudodoki
