### ISSUE TITLE
Am I supposed to just read the docs?

### ISSUE THREAD

**Issue by stkb** [robertkowalski/learnyoucouchdb#3]
I did the first lesson and installed CouchDB and the lesson verified successfully. Now on to lesson 2; it says: 

"Start Apache CouchDB and create a database named couchdbschool by using HTTP.
After you created the database, please insert this document: [..]"

Erm have I missed something? because I don't know how to do any of that yet. Should I be reading the CouchDB docs to learn how? Because then it seems I could just do the tutorial on there instead

**Comment by Kalevera** [comment]
What machine are you running this on? 

At any rate I did the second tutorial and the third tutorial all within the browser. 
I'm running on windows8.1 and using node. This has allowed me to start two instances of he CMD. 

Anyways run learnyoucouchdb. erl boots up the database on localhost 127.0.0.1:5984.
But what does that mean? when I navigate to the location in my browser it doesn't show anything. 
add /_utils so the above looks like 127.0.0.1:5984/_utils

This will bring up Futon! i don't know what that really means yet but it's a nice gui to interact with the database. I've seen three ways to create the design view stuff but the easiest is to use the drop down menu. The views menu is located above the database on the right hand side next to a gray "view label" (IMO was hard to see and I never found it for three days!) 

click it. Select temp view. This is a nifty feature to check your "design" and "view" code when populating the design view. type your code then test it by clicking "run" 

When you get what you want click save-as and label it accordingly. If you're doing the tutorial from nodeschool label both the design and the view correctly. 

Hope this helps. like I said above took me 3days! to get this far.

**Comment by stkb** [comment]
Thanks. I'm on Windows 8.1 too. I think you're supposed to do the tutorials using the http api but I guess using Futon will work too. I'll give it a try!

**Comment by Kalevera** [comment]
any luck? Btw if you're looking for a more command line approach someone from the CouchDB IRC pointed me to a neat NPM called Nano for communicating to couchDb it looks promising at first glance but I haven't gotten to toy with it. I mention this since you said Futon isn't quite what the tutorial was asking for.
